services:
  wazuh.manager:
    hostname: wazuh.manager
    image: wazuh/wazuh-manager:${WAZUH_DOCKER_TAG-latest}
    container_name: wazuh-manager
    security_opt:
      - no-new-privileges:true    
    env_file:
      - .env
      - ../.env         
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
      - ./config/rules/local_rules.xml:/var/ossec/etc/rules/local_rules.xml:ro
    networks:
      - wazuh
      - proxy
    ports:
      - 1514:1514
      - 1515:1515
      - 514:514/udp
      - 55000:55000
    restart: unless-stopped

  wazuh.indexer:
    hostname: wazuh.indexer
    image: wazuh/wazuh-indexer:${WAZUH_DOCKER_TAG-latest}
    container_name: wazuh-indexer
    security_opt:
      - no-new-privileges:true    
    env_file:
      - .env
      - ../.env         
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    networks:
      - wazuh
    # ports:
    #   - 9200:9200
    restart: unless-stopped

  wazuh.dashboard:
    hostname: wazuh.dashboard
    image: wazuh/wazuh-dashboard:${WAZUH_DOCKER_TAG-latest}
    container_name: wazuh-dashboard
    security_opt:
      - no-new-privileges:true    
    env_file:
      - .env
      - ../.env  
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      - ./config/certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    networks:
      - wazuh
      - proxy
    # ports:
    #   - 4443:5601
    depends_on:
      - wazuh.indexer
    restart: unless-stopped
    labels:
        - traefik.enable=true
        - traefik.http.routers.wazuh-rtr.entrypoints=websecure
        - traefik.http.routers.wazuh-rtr.rule=Host(`wazuh.$DOMAINNAME`)
        - traefik.http.routers.wazuh-rtr.middlewares=chain-no-auth@file
        - traefik.http.routers.wazuh-rtr.service=wazuh-svc
        - traefik.http.services.wazuh-svc.loadbalancer.server.port=5601
        - traefik.http.services.wazuh-svc.loadbalancer.server.scheme=https   
        - traefik.http.services.wazuh-svc.loadbalancer.serversTransport=skipverify@file       

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:

networks:
  wazuh:
    internal: true
    name: wazuh
    ipam:
      config:
        - subnet: 10.10.0.16/29
  proxy:
    external: true

