services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:${SPEEDTEST_TRACKER_DOCKER_TAG-latest}
    security_opt:
      - no-new-privileges:true    
    env_file:
      - .env
      - ../.env   
    volumes:
      - ./config:/config
    networks:
      - proxy
    # ports:
    #   - ${SPEEDTEST_TRACKER_PORT-80}:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-tracker-rtr.entrypoints=websecure"
      - "traefik.http.routers.speedtest-tracker-rtr.rule=Host(`speed-tracker.$DOMAINNAME`)"
      - "traefik.http.routers.speedtest-tracker-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.speedtest-tracker-rtr.service=speedtest-tracker-svc"
      - "traefik.http.services.speedtest-tracker-svc.loadbalancer.server.port=80"         

networks:
  proxy:
    external: true