http:
  middlewares:
    chain-authentik:
      chain:
        middlewares:
          # - middlewares-crowdsec-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authentik
      