http:
  middlewares:
    pihole-redirect:
      redirectRegex:
        permanent: true
        regex: ^https://pihole.{{env "DOMAINNAME"}}/?$
        replacement: https://pihole.{{env "DOMAINNAME"}}/admin      