services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:${IT_TOOLS_DOCKER_TAG-latest}
    security_opt:
    - no-new-privileges:true
    env_file:
      -  .env
      -  ../.env
    networks:
      - proxy
    # ports:
    #   - ${IT_TOOLS_PORT-8080}:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools-rtr.entrypoints=websecure
      - traefik.http.routers.it-tools-rtr.rule=Host(`it-tools.$DOMAINNAME`) || Host(`tools.$DOMAINNAME`)
      - traefik.http.routers.it-tools-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.it-tools-rtr.service=it-tools-svc
      - traefik.http.services.it-tools-svc.loadbalancer.server.port=80

networks:
  proxy:
    external: true