services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:${SONARR_DOCKER_TAG-latest}
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
      - ../.env      
    networks:
      - proxy
    # ports:
    #   - ${SONARR_PORT-8989}:8989
    volumes:
      - ./sonarr:/config
      - /media/media/tv:/tv
      - /media/downloads/data/complete:/data/complete
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-rtr.entrypoints=websecure
      - traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.$DOMAINNAME`)
      - traefik.http.routers.sonarr-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.sonarr-rtr.service=sonarr-svc
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989 
    restart: unless-stopped