services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VAULTWARDEN_DOCKER_TAG-latest}
    security_opt:
      - no-new-privileges:true    
    env_file:
      - .env
      - ../.env      
    volumes:
      - ./config:/data/
    networks:
      - proxy
    # ports:
    #   - ${VAULTWARDEN_PORT-80}:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden-rtr.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-rtr.rule=Host(`vaultwarden.$DOMAINNAME`) || Host(`bitwarden.$DOMAINNAME`)"
      - "traefik.http.routers.vaultwarden-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.vaultwarden-rtr.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadbalancer.server.port=80"

networks:
  proxy:
    external: true