services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_DOCKER_TAG-latest}
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./.env
      - ../.env
    volumes:
      - portainer_data:/data
    networks:
      - socket_proxy
      - proxy
    # ports:
    #   - ${PORTAINER_HTTP_PORT-9000}:9000
    #   - ${PORTAINER_HTTPS_PORT-9443}:9443
    command: -H tcp://socket-proxy:2375
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-rtr.entrypoints=websecure
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)
      - traefik.http.routers.portainer-rtr.middlewares=chain-no-auth@file
      - traefik.http.routers.portainer-rtr.service=portainer-svc
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000

volumes:
  portainer_data:

networks:
  proxy:
    external: true   
  socket_proxy:
    external: true