services:
  socket-proxy:
    container_name: socket-proxy
    image: lscr.io/linuxserver/socket-proxy:${SOCKET_PROXY_DOCKER_TAG-latest}
    security_opt:
    - no-new-privileges:true         
    read_only: true    
    env_file:
      - ../.env
    environment:
      - LOG_LEVEL=info
      - ALLOW_START=0 #optional
      - ALLOW_STOP=0 #optional
      - ALLOW_RESTARTS=0 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 # Traefik, portainer
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0 #optional
      - PING=1 #optional
      - PLUGINS=0 #optional
      - POST=0 #optional
      - PROXY_READ_TIMEOUT=240 #optional
      - SECRETS=0 #optional
      - SERVICES=1 # Portainer
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=1 # Portainer
      - VERSION=1 #optional
      - VOLUMES=1 # Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy      
    tmpfs:
      - /run
    restart: unless-stopped

networks:
  socket_proxy:
    name: socket_proxy
    internal: true  
    ipam:
      config:
        - subnet: 172.16.0.0/28 #needs to be adjusted as more services require access to the socket-proxy
